kind: Grafana
apiVersion: integreatly.org/v1alpha1
metadata:
  namespace: snmp-demo
  name: grafana-snmp-demo
  labels:
    team: demo
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: secret
      admin_user: root
  dashboardLabelSelector:
    - matchLabels:
        team: demo
