{
 "title": "SNMP Exporter Demo",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(memTotalReal-memAvailReal)/memTotalReal",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "laLoadFloat{laIndex=\"1\"}",
     "legendFormat": "1 Minute Average"
    },
    {
     "expr": "laLoadFloat{laIndex=\"2\"}",
     "legendFormat": "5 Minute Average"
    },
    {
     "expr": "laLoadFloat{laIndex=\"3\"}",
     "legendFormat": "15 Minute Average"
    }
   ]
  },
  {
   "title": "Interfaces Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{ifIndex=\"3\"}",
     "legendFormat": "ETH"
    },
    {
     "expr": "ifOperStatus{ifIndex=\"1\"}",
     "legendFormat": "LO"
    }
   ]
  },
  {
   "title": "Input Octets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifInOctets{ifIndex=\"3\"}[1m])",
     "legendFormat": "eth"
    },
    {
     "expr": "irate(ifInOctets{ifIndex=\"1\"}[1m])",
     "legendFormat": "lo"
    }
   ]
  },
  {
   "title": "Output Octects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutOctets{ifIndex=\"3\"}[1m])",
     "legendFormat": "eth"
    },
    {
     "expr": "irate(ifOutOctets{ifIndex=\"1\"}[1m])",
     "legendFormat": "lo"
    }
   ]
  }
 ]
}